services:
  - docker

branches:
  only:
    - master

  #Pre-testing installs
install:
  - echo "no install"

#script to be run such as tests

before_script:
  - echo "no tests"

script:
  - docker --version #print docker version
  - docker build -t nginx .
  - docker tag nginx waqasnoor/nginx:latest
  - docker tag nginx waqasnoor/nginx:"$TRAVIS_BUILD_NUMBER"

# Tasks to perform after image
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push waqasnoor/nginx:"$TRAVIS_BUILD_NUMBER"
  - docker push waqasnoor/nginx:latest
